### ISSUE TITLE
Error: Cannot find module 'babel-plugin-macros'

### ISSUE THREAD

**Issue by aurelien-reeves** [DevExpress/testcafe-action#20] opened 2020-12-17 11:12 UTC
The action stopped working without any change in the workflow with "Error: Cannot find module 'babel-plugin-macros'"

The workflow is really simple:
```yaml
    - name: Execute testCafé tests
      uses: DevExpress/testcafe-action@latest
      env:
        // **secrets**
```

Before today, it has been executed 10 days ago successfully.

Following more logs:
```
Run DevExpress/testcafe-action@latest
  with:
    version: latest
  env:
    JIRA_USER_EMAIL: ***
    JIRA_USER_PASSWORD: ***
VERSION: latest
BRANCH: not specified
COMMIT: not specified
Installing TestCafe from npm...
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
Running TestCafe...
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm notice created a lockfile as package-lock.json. You should commit this file.
ERROR Error: Cannot find module 'babel-plugin-macros'
```

**Comment by miherlosev** [comment] 2020-12-21 07:53
Hi @aurelien-reeves,

Thank you for reporting this issue. I will close it as it is a duplicate of this thread: https://github.com/DevExpress/testcafe/issues/5808.

**Closed as completed by miherlosev** 2020-12-21 07:53 UTC

**Comment by aurelien-reeves** [comment] 2020-12-21 13:06
Ok, thanks for the info.
